### ISSUE TITLE
Different version of Artifice in different mods will cause the game to crash

### ISSUE THREAD

**Issue by linzexin022** [natanfudge/artifice#27]
Found this problem when using different mods which have in-jar artifices with different versions.

[Issue about Phonos (artifice 0.14.4) and Slabref (artifice 0.13.2)](https://github.com/CebbysMods/slabref-mod/issues/5)

[Issue about Phonos (artifice 0.14.4) and Iron Jetpack (artifice 0.13.2)](https://github.com/FoundationGames/Phonos/issues/6)

**Comment by natanfudge** [comment]
wont fix (for older versions. I hope in the future changes will be done better.)
