### ISSUE TITLE
[1.15.2] Crash when registering a data pack

### ISSUE THREAD

**Issue by MarioAndWeegee3** [natanfudge/artifice#3]
https://pastebin.com/bvhmN0jv
https://github.com/MarioAndWeegee3/Tool-Builder

The game crashes when started as a server. I think this is caused by ClientResourcePackProfile being Client-only in 1.15.2.

**Comment by natanfudge** [comment]
I'll have a look at it today

**Comment by natanfudge** [comment]
This should be fixed as of `0.6.0+1.15.2`. This build will work for previous versions of Minecraft as well, but is not binary/source compatible with `0.5.x`.
