### ISSUE TITLE
1.15.2 - crash on server load 

### ISSUE THREAD

**Issue by SDUBZ** [natanfudge/artifice#4]
artifice version used artifice-0.5.1+1.15.1.jar
log:
http://puu.sh/F5cTj/161eb505e8.log

**Comment by natanfudge** [comment]
@SDUBZ  Can you check if the issue persists in `0.6.0+1.15.2`?

**Comment by SDUBZ** [comment]
okay i can

**Comment by SDUBZ** [comment]
[latest.log](https://github.com/natanfudge/artifice/files/4134159/latest.log)
yepp still happens @natanfudge

**Comment by natanfudge** [comment]
This doesn't happen to me when I run the game, can you tell me the steps needed to reproduce this?

**Comment by SDUBZ** [comment]
it was on toolbuilders end now its fixed closing
