### ISSUE TITLE
1.16.1

### ISSUE THREAD

**Issue by dranorter** [natanfudge/artifice#8]
I'm trying to get the Extra Pieces project to build for 1.16.1 and right now I'm confronted with "fabric-object-builder-api-v1-1.5.5+e00ecb5f7c.jar contains an access widener. The current version of loom does not support this. Please update to loom 0.2.7 or higher." Near as I can guess, that's because artifice is at version 1.16 pre1. Is this going to be updated? Should I try to do it?

**Comment by arthurbambou** [comment]
You need to change your version of Loom in build.gradle to 0.4-SNAPSHOT

**Comment by dranorter** [comment]
When I do that, I'm getting "Can't find the resource index file: C:\Users\drano\.gradle\caches\fabric-loom\assets\indexes\1.16.1-1.16.json" followed by "java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll" (I tried adding the lwjgl jar to classpath, but that didn't work and it seems clear I shouldn't have to.)

**Comment by natanfudge** [comment]
do `gradlew --refresh-dependencies` and restart your IDE
